config/routes.rb
Rails.application.routes.draw do
  resources :map_element_locations

  resources :maps

  resources :element_types

  resources :element_connections

  resources :element_aviable_attributes

  resources :element_attributes

  resources :elements

  resources :attributes

  root to: 'elements#index'
end

app/models/element.rb
class Element < ActiveRecord::Base
    self.table_name = 'element'


    belongs_to :element_type, :class_name => 'ElementType', :foreign_key => :element_type_id
    has_many :element_attributes, :class_name => 'ElementAttribute'
    has_many :element_connections, :class_name => 'ElementConnection'
    has_many :element_connections, :class_name => 'ElementConnection'
    has_many :map_element_locations, :class_name => 'MapElementLocation'
end

app/models/element_type.rb
class ElementType < ActiveRecord::Base
    self.table_name = 'element_type'


    has_many :elements, :class_name => 'Element'
    has_many :element_aviable_attributes, :class_name => 'ElementAviableAttribute'
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: [:show, :edit, :update, :destroy]

  def index
    @elements = Element.all
    respond_with(@elements)
  end

  def show
    respond_with(@element)
  end

  def new
    @element = Element.new
    respond_with(@element)
  end

  def edit
  end

  def create
    @element = Element.new(element_params)
    @element.save
    respond_with(@element)
  end

  def update
    @element.update(element_params)
    respond_with(@element)
  end

  def destroy
    @element.destroy
    respond_with(@element)
  end

  private
    def set_element
      @element = Element.find(params[:id])
    end

    def element_params
      params.require(:element).permit(:element_type_id, :name, :is_pattern)
    end
end

app/views/elements/_form.html.haml
= simple_form_for @element do |f|
  - if @element.errors.any?
    #error_explanation
      %h2= "#{pluralize(@element.errors.count, "error")} prohibited this element from being saved:"
      %ul
        - @element.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.association :element_type
  .field
    = f.input :name
  .field
    = f.input :is_pattern, as: :boolean
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/elements/edit.html.haml
%h1 Editing element

= render 'form'

= link_to 'Show', @element, class: 'btn btn-default'

= link_to 'Back', elements_path, class: 'btn btn-default'

app/views/elements/index.html.haml
%h1 Listing elements

%table.table
  %thead
    %tr
      %th Element type
      %th Name
      %th Is pattern
      %th
      %th
      %th

  %tbody
    - @elements.each do |element|
      %tr
        %td= element.element_type.name
        %td= element.name
        %td= element.is_pattern
        %td= link_to 'Show', element, class: 'btn btn-default'
        %td= link_to 'Edit', edit_element_path(element), class: 'btn btn-default'
        %td= link_to 'Destroy', element, class: 'btn btn-danger', :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Element', new_element_path, class: 'btn btn-primary'

app/views/elements/new.html.haml
%h1 New element

= render 'form'

= link_to 'Back', elements_path, class: 'btn btn-default'

app/views/elements/show.html.haml
%p#notice= notice

%p
  %b Element type:
  = @element.element_type.name
%p
  %b Name:
  = @element.name
%p
  %b Is pattern:
  = @element.is_pattern

= link_to 'Edit', edit_element_path(@element), class: 'btn btn-default'

= link_to 'Back', elements_path, class: 'btn btn-default'