config/routes.rb
Rails.application.routes.draw do
  resources :map_element_locations

  resources :maps

  resources :element_types

  resources :element_connections

  resources :element_aviable_attributes

  resources :element_attributes

  resources :elements

  resources :attributes

  root to: 'elements#index'
end

app/models/map.rb
class Map < ActiveRecord::Base
    self.table_name = 'map'

    validates :max_x_cord, :max_y_cord, :background_url, :name, presence: true
    has_many :map_element_locations, :class_name => 'MapElementLocation'
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  def index
    @maps = Map.all
    respond_with(@maps)
  end

  def show
    respond_with(@map)
  end

  def new
    @map = Map.new
    respond_with(@map)
  end

  def edit
  end

  def create
    @map = Map.new(map_params)
    @map.save
    respond_with(@map)
  end

  def update
    @map.update(map_params)
    respond_with(@map)
  end

  def destroy
    @map.destroy
    respond_with(@map)
  end

  private
    def set_map
      @map = Map.find(params[:id])
    end

    def map_params
      params.require(:map).permit(:name, :max_x_cord, :max_y_cord, :background_url)
    end
end

app/views/maps/_form.html.haml
= simple_form_for @map do |f|
  - if @map.errors.any?
    #error_explanation
      %h2= "#{pluralize(@map.errors.count, "error")} prohibited this map from being saved:"
      %ul
        - @map.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :name
  .field
    = f.input :max_x_cord
  .field
    = f.input :max_y_cord
  .field
    = f.input :background_url
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/maps/edit.html.haml
%h1 Editing map

= render 'form'

= link_to 'Show', @map, class: 'btn btn-default'

= link_to 'Back', maps_path, class: 'btn btn-default'

app/views/maps/index.html.haml
%h1 Listing maps

%table.table
  %thead
    %tr
      %th Name
      %th Max x cord
      %th Max y cord
      %th Background url
      %th
      %th
      %th

  %tbody
    - @maps.each do |map|
      %tr
        %td= map.name
        %td= map.max_x_cord
        %td= map.max_y_cord
        %td= map.background_url
        %td= link_to 'Show', map, class: 'btn btn-default'
        %td= link_to 'Edit', edit_map_path(map), class: 'btn btn-default'
        %td= link_to 'Destroy', map, class: 'btn btn-danger', :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Map', new_map_path, class: 'btn btn-primary'

app/views/maps/new.html.haml
%h1 New map

= render 'form'

= link_to 'Back', maps_path, class: 'btn btn-default'

app/views/maps/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @map.name
%p
  %b Max x cord:
  = @map.max_x_cord
%p
  %b Max y cord:
  = @map.max_y_cord
%p
  %b Background url:
  = @map.background_url

= link_to 'Edit', edit_map_path(@map), class: 'btn btn-default'

= link_to 'Back', maps_path, class: 'btn btn-default'