config/routes.rb
Rails.application.routes.draw do
  resources :map_element_locations

  resources :maps

  resources :element_types

  resources :element_connections

  resources :element_aviable_attributes

  resources :element_attributes

  resources :elements

  resources :attributes

  root to: 'elements#index'
end

app/models/element_connection.rb
class ElementConnection < ActiveRecord::Base
    self.table_name = 'element_connection'

    validates :element, :element2, :connection_type, presence: true

    belongs_to :element,  :class_name => 'Element', :foreign_key => :element_id
    belongs_to :element2, :class_name => 'Element', :foreign_key => :element_id2
end

app/controllers/element_connections_controller.rb
class ElementConnectionsController < ApplicationController
  before_action :set_element_connection, only: [:show, :edit, :update, :destroy]

  def index
    @element_connections = ElementConnection.all
    respond_with(@element_connections)
  end

  def show
    respond_with(@element_connection)
  end

  def new
    @element_connection = ElementConnection.new
    respond_with(@element_connection)
  end

  def edit
  end

  def create
    @element_connection = ElementConnection.new(element_connection_params)
    @element_connection.save
    respond_with(@element_connection)
  end

  def update
    @element_connection.update(element_connection_params)
    respond_with(@element_connection)
  end

  def destroy
    @element_connection.destroy
    respond_with(@element_connection)
  end

  private
    def set_element_connection
      @element_connection = ElementConnection.find(params[:id])
    end

    def element_connection_params
      params.require(:element_connection).permit(:connection_type, :element_id, :element_id2, :parameters)
    end
end

app/views/element_connections/_form.html.haml
= simple_form_for @element_connection do |f|
  - if @element_connection.errors.any?
    #error_explanation
      %h2= "#{pluralize(@element_connection.errors.count, "error")} prohibited this element_connection from being saved:"
      %ul
        - @element_connection.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :connection_type
  .field
    = f.association :element
  .field
    = f.association :element2
  .field
    = f.input :parameters
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/element_connections/edit.html.haml
%h1 Editing element_connection

= render 'form'

= link_to 'Show', @element_connection, class: 'btn btn-default'

= link_to 'Back', element_connections_path, class: 'btn btn-default'

app/views/element_connections/index.html.haml
%h1 Listing element_connections

%table.table
  %thead
    %tr
      %th Connection type
      %th Element
      %th Second element
      %th Parameters
      %th
      %th
      %th

  %tbody
    - @element_connections.each do |element_connection|
      %tr
        %td= element_connection.connection_type
        %td= element_connection.element.try(:name)
        %td= element_connection.element2.try(:name)
        %td= element_connection.parameters
        %td= link_to 'Show', element_connection, class: 'btn btn-default'
        %td= link_to 'Edit', edit_element_connection_path(element_connection), class: 'btn btn-default'
        %td= link_to 'Destroy', element_connection, class: 'btn btn-danger', :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Element connection', new_element_connection_path, class: 'btn btn-primary'

app/views/element_connections/new.html.haml
%h1 New element_connection

= render 'form'

= link_to 'Back', element_connections_path, class: 'btn btn-default'

app/views/element_connections/show.html.haml
%p#notice= notice

%p
  %b Connection type:
  = @element_connection.connection_type
%p
  %b Element:
  = @element_connection.element.try(:name)
%p
  %b Second element:
  = @element_connection.element2.try(:name)
%p
  %b Parameters:
  = @element_connection.parameters

= link_to 'Edit', edit_element_connection_path(@element_connection), class: 'btn btn-default'

= link_to 'Back', element_connections_path, class: 'btn btn-default'