config/routes.rb
Rails.application.routes.draw do
  resources :map_element_locations

  resources :maps

  resources :element_types

  resources :element_connections

  resources :element_aviable_attributes

  resources :element_attributes

  resources :elements

  resources :attributes

  root to: 'elements#index'
end

app/models/map_element_location.rb
class MapElementLocation < ActiveRecord::Base
    self.table_name = 'map_element_location'

    validates :element, :map, :x_map_cord, :y_map_cord, presence: true

    belongs_to :map, :class_name => 'Map', :foreign_key => :map_id
    belongs_to :map_element_location, :class_name => 'MapElementLocation', :foreign_key => :id_parent
    belongs_to :element, :class_name => 'Element', :foreign_key => :element_id

    has_many :children, class_name: self.name, foreign_key: 'id_parent'
    belongs_to :parent, class_name: self.name, foreign_key: 'id_parent'
end

app/controllers/map_element_locations_controller.rb
class MapElementLocationsController < ApplicationController
  before_action :set_map_element_location, only: [:show, :edit, :update, :destroy]

  def index
    if params[:id_parent].present?
      @parent = MapElementLocation.find params[:id_parent]
      @map_element_locations = MapElementLocation.where(id_parent: params[:id_parent])
    else
      @map_element_locations = MapElementLocation.where(id_parent: nil)
    end
    respond_with(@map_element_locations)
  end

  def show
    respond_with(@map_element_location)
  end

  def new
    @map_element_location = MapElementLocation.new
    respond_with(@map_element_location)
  end

  def edit
  end

  def create
    @map_element_location = MapElementLocation.new(map_element_location_params)
    @map_element_location.save
    respond_with(@map_element_location)
  end

  def update
    @map_element_location.update(map_element_location_params)
    respond_with(@map_element_location)
  end

  def destroy
    @map_element_location.destroy
    respond_with(@map_element_location)
  end

  private
    def set_map_element_location
      @map_element_location = MapElementLocation.find(params[:id])
    end

    def map_element_location_params
      params.require(:map_element_location).permit(:id_parent, :element_id, :map_id, :x_map_cord, :y_map_cord, :parent_element_cord1, :parent_element_cord2, :parent_element_cord3)
    end
end

app/views/map_element_locations/_form.html.haml
= simple_form_for @map_element_location do |f|
  - if @map_element_location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@map_element_location.errors.count, "error")} prohibited this map_element_location from being saved:"
      %ul
        - @map_element_location.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.association :parent
  .field
    = f.association :element
  .field
    = f.association :map
  .field
    = f.input :x_map_cord
  .field
    = f.input :y_map_cord
  .field
    = f.input :parent_element_cord1
  .field
    = f.input :parent_element_cord2
  .field
    = f.input :parent_element_cord3
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/map_element_locations/edit.html.haml
%h1 Editing map_element_location

= render 'form'

= link_to 'Show', @map_element_location, class: 'btn btn-default'

= link_to 'Back', map_element_locations_path, class: 'btn btn-default'

app/views/map_element_locations/index.html.haml
%h1.headline Listing map_element_locations

- if @parent
  %p="Children of #{@parent.element.name}"
  %p
    You can
    = link_to 'go up', map_element_locations_path(id_parent: @parent.parent.try(:id))

%table.table
  %thead
    %tr
      %th Id parent
      %th Element
      %th Map
      %th X map cord
      %th Y map cord
      %th Parent element cord1
      %th Parent element cord2
      %th Parent element cord3
      %th
      %th
      %th
      %th

  %tbody
    - @map_element_locations.each do |map_element_location|
      %tr
        %td= map_element_location.parent.try(:element).try(:name)
        %td= map_element_location.element.name
        %td= map_element_location.map.name
        %td= map_element_location.x_map_cord
        %td= map_element_location.y_map_cord
        %td= map_element_location.parent_element_cord1
        %td= map_element_location.parent_element_cord2
        %td= map_element_location.parent_element_cord3
        %td
          = link_to 'Children', map_element_locations_path(id_parent: map_element_location.id), class: 'btn btn-default' if map_element_location.children.any?
        %td= link_to 'Show', map_element_location, class: 'btn btn-default'
        %td= link_to 'Edit', edit_map_element_location_path(map_element_location), class: 'btn btn-default'
        %td= link_to 'Destroy', map_element_location, class: 'btn btn-danger', :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Map element location', new_map_element_location_path, class: 'btn btn-primary'

app/views/map_element_locations/new.html.haml
%h1 New map_element_location

= render 'form'

= link_to 'Back', map_element_locations_path, class: 'btn btn-default'

app/views/map_element_locations/show.html.haml
%p#notice= notice

%p
  %b Id parent:
  = @map_element_location.id_parent
%p
  %b Element:
  = @map_element_location.element
%p
  %b Map:
  = @map_element_location.map
%p
  %b X map cord:
  = @map_element_location.x_map_cord
%p
  %b Y map cord:
  = @map_element_location.y_map_cord
%p
  %b Parent element cord1:
  = @map_element_location.parent_element_cord1
%p
  %b Parent element cord2:
  = @map_element_location.parent_element_cord2
%p
  %b Parent element cord3:
  = @map_element_location.parent_element_cord3

= link_to 'Edit', edit_map_element_location_path(@map_element_location), class: 'btn btn-default'

= link_to 'Back', map_element_locations_path, class: 'btn btn-default'